<template>
  <div class="app-container">
    <div class="filter-container">
      <el-input
        v-model="listQuery.search"
        placeholder="Search Records"
        style="width: 200px;"
        class="filter-item"
        @keyup.enter.native="handleFilter"
      />
      <el-button
        v-waves
        class="filter-item"
        type="primary"
        icon="el-icon-search"
        @click="handleFilter"
      >Search</el-button>
     <!--  <el-button
        class="filter-item"
        style="margin-left: 10px;"
        type="success"
        icon="el-icon-refresh-left"
        @click="handleCreate"
      > Generate</el-button> -->
      <el-button
        v-waves
        :loading="downloadLoading"
        class="filter-item"
        type="warning"
        icon="el-icon-download"
        @click="handleDownload"
      >Export</el-button>
    </div>

    <el-table
      :key="tableKey"
      v-loading="listLoading"
      :data="list"
      border
      fit
      highlight-current-row
      style="width: 100%;"
      @sort-change="sortChange"
    >
      <el-table-column type="expand">
        <template slot-scope="{row}">
          <div v-for="income in row.incomes">
            <p><b>Name:</b> {{ income.income.name }}</p>
            <p><b>Payout Amount:</b> {{ income.payout_amount}}</p>
            <p v-if="income.income_payout_parameter_1_name" ><b>{{income.income_payout_parameter_1_name}}</b> {{income.income_payout_parameter_1_value}}</p>
            <p v-if="income.income_payout_parameter_2_name" ><b>{{income.income_payout_parameter_2_name}}</b> {{income.income_payout_parameter_2_value}}</p>
            <p v-if="income.income_payout_parameter_3_name" ><b>{{income.income_payout_parameter_3_name}}</b> {{income.income_payout_parameter_3_value}}</p>
            <p v-if="income.income_payout_parameter_4_name" ><b>{{income.income_payout_parameter_4_name}}</b> {{income.income_payout_parameter_4_value}}</p>
            <p v-if="income.income_payout_parameter_5_name" ><b>{{income.income_payout_parameter_5_name}}</b> {{income.income_payout_parameter_5_value}}</p><br>
          </div>
        </template>
      </el-table-column>

      <el-table-column
        label="ID"
        prop="id"
        sortable="custom"
        align="center"
        width="80"
        :class-name="getSortClass('id')"
      >
        <template slot-scope="{row}">
          <span>{{ row.id }}</span>
        </template>
      </el-table-column>
      
      <el-table-column label="Payout Type" min-width="150px" align="center">
        <template slot-scope="{row}">
          <span >{{ row.payout_type?row.payout_type.name:'' }}</span>
        </template>
      </el-table-column>
     <!--  <el-table-column label="Generated by System?" class-name="status-col" width="200">
        <template slot-scope="{row}">
          <el-tag :type="row.is_run_by_system | statusFilter">{{ row.is_run_by_system?'Yes':'No' }}</el-tag>
        </template>
      </el-table-column> -->

      <el-table-column label="Sales Start Date" width="150px" align="center">
        <template slot-scope="{row}">
          <span>{{ row.sales_start_date | parseTime('{y}-{m}-{d}') }}</span>
        </template>
      </el-table-column>
      <el-table-column label="Sales End Date" width="150px" align="center">
        <template slot-scope="{row}">
          <span>{{ row.sales_end_date | parseTime('{y}-{m}-{d}') }}</span>
        </template>
      </el-table-column>
      <el-table-column label="Sales BV" width="130px" align="right">
        <template slot-scope="{row}">
          <span >{{ row.sales_bv }}</span>
        </template>
      </el-table-column>
      <el-table-column label="GST" width="130px" align="right">
        <template slot-scope="{row}">
          <span >{{ row.sales_gst }}</span>
        </template>
      </el-table-column>
      <el-table-column label="Shipping" width="130px" align="right">
        <template slot-scope="{row}">
          <span >{{ row.sales_shipping_fee }}</span>
        </template>
      </el-table-column>
      <el-table-column label="Sales Amount" width="130px" align="right">
        <template slot-scope="{row}">
          <span >{{ row.sales_amount }}</span>
        </template>
      </el-table-column>
      <el-table-column label="Total Matched" width="130px" align="right">
        <template slot-scope="{row}">
          <span >{{ row.total_matched_bv }}</span>
        </template>
      </el-table-column>
      <el-table-column label="Carry Forwarded" width="150px" align="right">
        <template slot-scope="{row}">
          <span >{{ row.total_carry_forward_bv }}</span>
        </template>
      </el-table-column>
      <el-table-column label="Total Payout" width="130px" align="right">
        <template slot-scope="{row}">
          <span >{{ row.payout_amount }}</span>
        </template>
      </el-table-column>
      <el-table-column label="TDS" width="130px" align="right">
        <template slot-scope="{row}">
          <span >{{ row.tds }}</span>
        </template>
      </el-table-column>
      <el-table-column label="Admin Fee" width="120px" align="right">
        <template slot-scope="{row}">
          <span >{{ row.admin_fee }}</span>
        </template>
      </el-table-column>
      <el-table-column label="Payable" width="130px" align="right">
        <template slot-scope="{row}">
          <span >{{ row.net_payable_amount }}</span>
        </template>
      </el-table-column>

       <el-table-column label="Generated at" width="150px" align="center">
        <template slot-scope="{row}">
          <span>{{ row.created_at | parseTime('{y}-{m}-{d}') }}</span>
        </template>
      </el-table-column>
    </el-table>

    <pagination
      v-show="total>0"
      :total="total"
      :page.sync="listQuery.page"
      :limit.sync="listQuery.limit"
      @pagination="getList"
    />

    <el-dialog :title="dialogTitle" width="50%" top="30px"  :visible.sync="dialogPayoutGenerateVisible">
      <el-form ref="payoutGenerateForm" :rules="rules" :model="temp" style="">
        <el-row :gutter="20">
          
          <el-col  :xs="24" :sm="24" :md="24" :lg="24" :xl="24" >
            <el-form-item label="Sales date range" prop="date_range">
              <br>
              <div class="block">
                <el-date-picker
                style="width:100%"
                  v-model="temp.date_range"
                  type="daterange"
                  align="right"
                  unlink-panels
                  format="yyyy-MM-dd"
                  value-format="yyyy-MM-dd"
                  range-separator="To"
                  start-placeholder="Sale Start date"
                  end-placeholder="Sale End date">
                </el-date-picker>
              </div>
            </el-form-item>
            <el-form-item label="Incomes" prop="incomes">
                <el-select v-model="temp.incomes" multiple clearable  style="width:100%;" filterable placeholder="Select Incomes">
                  <el-option
                    v-for="item in income_list"
                    :key="item.name"
                    :label="item.name"
                    :value="item.id">
                  </el-option>
                </el-select>
              </el-form-item>
          </el-col>

        </el-row>
      </el-form>
      <div slot="footer" class="dialog-footer">
        <el-button @click="dialogPayoutGenerateVisible = false">
          Cancel
        </el-button>
        <el-button type="primary" icon="el-icon-finished" :loading="buttonLoading" @click="dialogStatus==='create'?createData():updateData()">
          Save
        </el-button>
      </div>
    </el-dialog>
  </div>
</template>

<script>
import { fetchPayouts, generateManualPayout,} from "@/api/admin/payouts";
import { getAllIncomes,} from "@/api/admin/incomes";
import waves from "@/directive/waves"; // waves directive
import { parseTime } from "@/utils";
import Pagination from "@/components/Pagination"; 
import role from '@/directive/role'; 
import checkRole from '@/utils/role';

export default {
  name: "GeneratePayout",
  components: { Pagination },
  directives: { waves,role },
  filters: {
    statusFilter(status) {
      const statusMap = {
        1: "success",
        draft: "info",
        0: "danger"
      };

      return statusMap[status];
    }
  },
  data() {
    return {
      tableKey: 0,
      list: null,
      total: 0,
      listLoading: true,
      listQuery: {
        page: 1,
        limit: 10,
        search: undefined,
        sort: "-id"
      },
      sortOptions: [
        { label: "ID Ascending", key: "+id" },
        { label: "ID Descending", key: "-id" }
      ],
      temp: {
        date_range:undefined,
        incomes:undefined
      },
      income_list:[],
      pickerOptions: {
        shortcuts: [{
          text: 'Last week',
          onClick(picker) {
            const end = new Date();
            const start = new Date();
            start.setTime(start.getTime() - 3600 * 1000 * 24 * 7);
            picker.$emit('pick', [start, end]);
          }
        }, {
          text: 'Last month',
          onClick(picker) {
            const end = new Date();
            const start = new Date();
            start.setTime(start.getTime() - 3600 * 1000 * 24 * 30);
            picker.$emit('pick', [start, end]);
          }
        }, {
          text: 'Last 3 months',
          onClick(picker) {
            const end = new Date();
            const start = new Date();
            start.setTime(start.getTime() - 3600 * 1000 * 24 * 90);
            picker.$emit('pick', [start, end]);
          }
        }]
      },
      dialogPayoutGenerateVisible:false,
      dialogStatus: "",
      dialogTitle:"",
      textMap: {
        update: "Edit",
        create: "Create"
      },
      rules: {
        date_range: [{ required: true, message: 'Date range is required', trigger: 'blur' }],
        incomes: [{ required: true, message: 'Please select income', trigger: 'blur' }],
      },
      downloadLoading: false,
      buttonLoading: false
    };
  },
  created() {
    this.getList();
    getAllIncomes().then(response => {
      this.income_list = response.data;
    });
  },
  methods: {
    checkRole,
    getList() {
      this.listLoading = true;
      fetchPayouts(this.listQuery).then(response => {
        this.list = response.data.data;
        this.total = response.data.total;
        setTimeout(() => {
          this.listLoading = false;
        }, 1 * 100);
      });
    },
    handleFilter() {
      this.listQuery.page = 1;
      this.getList();
    },
    
    resetTemp() {
      this.temp = {
        id: undefined,
        date_range:undefined,
        incomes:undefined
      };
    },
    handleCreate() {
      this.resetTemp();
      this.dialogStatus = "create";
      this.dialogTitle="Generate Payout";
      this.dialogPayoutGenerateVisible = true;
      this.$nextTick(() => {
        this.$refs["payoutGenerateForm"].clearValidate();
      });
    },
    createData() {
      this.$refs["payoutGenerateForm"].validate(valid => {
        if (valid) {
          this.buttonLoading=true;
          generateManualPayout(this.temp).then((data) => {
            this.dialogPayoutGenerateVisible = false;
            this.$notify({
              title: "Success",
              message: data.message,
              type: "success",
              duration: 2000
            });
            this.buttonLoading=false;
            this.resetTemp();
          }).catch((err)=>{
            this.buttonLoading=false;
          });
        }
      });      
    },
    sortChange(data) {
      const { prop, order } = data;
      if (prop === "id") {
        this.sortByID(order);
      }
    },
    sortByID(order) {
      if (order === "ascending") {
        this.listQuery.sort = "+id";
      } else {
        this.listQuery.sort = "-id";
      }
      this.handleFilter();
    },
    getSortClass: function(key) {
      const sort = this.listQuery.sort;
      return sort === `+${key}`
        ? "ascending"
        : sort === `-${key}`
        ? "descending"
        : "";
    },
    handleDownload() {
      this.downloadLoading = true;
      import("@/vendor/Export2Excel").then(excel => {
        const tHeader = [
          "Sr.No",
          "Sales start date",
          "Sales end date",
          "GST",
          "Courier",
          "Sales Amount",
          "Total BV",          
          "Total Payout",
          "Generated At",
        ];
        const filterVal = [
          "id",
          "sales_start_date",
          "sales_end_date",
          "sales_gst",
          "sales_shipping_fee",
          "sales_total_amount",
          "total_payout",
          "created_at",
        ];
        const data = this.formatJson(filterVal, this.list);
        excel.export_json_to_excel({
          header: tHeader,
          data,
          filename: "payouts"
        });
        this.downloadLoading = false;
      });
    },
    formatJson(filterVal, jsonData) {
      return jsonData.map(v =>
        filterVal.map(j => {
          if (j === "timestamp") {
            return parseTime(v[j]);
          } else if(j === "payout_type") {
            return v.payout_type?v.payout_type.name:''
          }else {
            return v[j];
          }
        })
      );
    },
  }
};
</script>

<style scoped>
.el-drawer__body {
  padding: 20px;
}
.pagination-container {
  margin-top: 5px;
}
.pagination-container {
  background: #fff;
  padding: 15px 16px;
}

</style>
